lwr:

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - lwr_a1_joint
      - lwr_a2_joint
      - lwr_e1_joint
      - lwr_a3_joint
      - lwr_a4_joint
      - lwr_a5_joint
      - lwr_a6_joint

  # Publish all joint states -----------------------------------
  kuka_joint_state_controller:
    type: lwr_controllers/KUKAJointStateController
    publish_rate: 100  
    root_name: lwr_base_link
    tip_name: lwr_7_link

  joint_controllers:
    type: lwr_controllers/JointControllers
    root_name: lwr_base_link
    tip_name: lwr_7_link
    max_ee_dt : 1
    max_ee_f : 5
    max_qdot : 3


